# IssueMyPy


The issue can be replicated by calling 
mypy test1.py
when this is called the error "Cannot find module named 'f1.test2'" is shown
